project:
  type: website
  output-dir: ./_site/es
  render:
    - "*.qmd"
  resources:
    - media-img/

website:
  search: false
  title: "Guillermo Solovey"
  navbar:
    pinned: true
    background: "#faf9f7"
    left:
      - href: ../es/index.html
        text: "{{< fa home >}}"
      - href: ../es/research.html
        text: "{{< fa newspaper >}} investigación"
      - href: ../es/teaching.html
        text: "{{< fa chalkboard-user >}} docencia"
      - href: ../es/grupo.html
        text: "{{< fa people-group >}} grupo"
      - href: ../es/media.html
        text: "{{< fa satellite-dish >}} medios"
      - href: ../es/CV-Solovey.pdf
        text: "{{< fa file >}} cv"
    right:
      - href: ../es/index.html
        text: "Español"
      - href: ../index.html
        text: "English"

  page-footer:
    background: "#faf9f7"
    right: |
      <a href="https://www.ic.fcen.uba.ar" target="_blank">Instituto de Cálculo</a>
      
lang: es

format:
  html:
    theme:
      - flatly
      - custom.scss
    fontsize: 1.05em
    linestretch: 1.5
    toc: true
    backgroundcolor: "#faf9f7"
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;1,400&display=swap" rel="stylesheet">

editor: visual

