project:
  type: website
  output-dir: ./_site
  render:
    - "*.qmd"

website:
  search: false
  title: "Guillermo Solovey"
  navbar:
    pinned: true
    background: "#ffffff"
    left:
      - href: ./index.html
        text: "{{< fa home >}}"
      - href: ./research.html
        text: "{{< fa newspaper >}} research"
      - href: ./teaching.html
        text: "{{< fa chalkboard-user >}} teaching"
      - href: ./grupo.html
        text: "{{< fa people-group >}} group"
      - href: ./media.html
        text: "{{< fa satellite-dish >}} media"
    right:
      - href: ./es/index.html
        text: "Español"
      - href: ./
        text: "English"

  page-footer:
    background: "#ffffff"
    right: |
      <a href="https://www.ic.fcen.uba.ar" target="_blank">Instituto de Cálculo</a>
      
lang: en

format:
  html:
    theme:
      - flatly
      - custom.scss
    fontsize: 1.05em
    linestretch: 1.5
    toc: true
    backgroundcolor: "#ffffff"

editor: visual

