---
title: ""
toc: false
editor: source
freeze: false
---


```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
library(fontawesome)
library(gsheet)
library(tidyverse)

html_esc <- function(x) {
  x <- gsub("&", "&amp;", as.character(x))
  x <- gsub("<", "&lt;", x)
  x <- gsub(">", "&gt;", x)
  x
}

render_entry <- function(p, use_pdf_col = FALSE, row_id = "0", year_label = "") {
  # Title
  t <- html_esc(p$title)
  title_html <- if (!is.na(p$url) && p$url != "")
    paste0('<a href="', p$url, '">', t, '</a>') else t

  # Journal on its own row
  journal_html <- if (!is.na(p$journaltitle) && p$journaltitle != "")
    paste0('<div class="pub-journal-row">', html_esc(p$journaltitle), '</div>\n') else ""

  # Links
  link_tags <- character(0)
  if (use_pdf_col && !is.na(p$pdf) && p$pdf != "")
    link_tags <- c(link_tags, paste0('<a href="/publications/', p$pdf, '">pdf</a>'))
  else if (!use_pdf_col && !is.na(p$url) && p$url != "")
    link_tags <- c(link_tags, paste0('<a href="', p$url, '">pdf</a>'))
  if (!is.na(p$github) && p$github != "")
    link_tags <- c(link_tags, paste0('<a href="', p$github, '">github</a>'))
  if (!is.na(p$osf) && p$osf != "")
    link_tags <- c(link_tags, paste0('<a href="', p$osf, '">osf</a>'))

  # Abstract
  has_abstract <- "abstract" %in% names(p) &&
                  !is.na(p$abstract) &&
                  nchar(trimws(as.character(p$abstract))) > 0
  abs_id <- paste0("abs-", row_id)

  abstract_btn <- ""
  abstract_div <- ""
  if (has_abstract) {
    abs_text <- trimws(as.character(p$abstract))
    abs_text <- gsub("\r?\n\r?\n", "</p><p>", abs_text)
    abs_text <- gsub("\r?\n", " ", abs_text)
    abstract_btn <- paste0(
      '<a class="abstract-toggle" data-bs-toggle="collapse" href="#', abs_id,
      '" role="button" aria-expanded="false">abstract</a>'
    )
    abstract_div <- paste0(
      '<div id="', abs_id, '" class="collapse abstract-body">',
      '<p>', abs_text, '</p></div>'
    )
  }

  all_links <- c(link_tags, if (has_abstract) abstract_btn else character(0))
  links_html <- if (length(all_links) > 0)
    paste0('<span class="pub-links">', paste(all_links, collapse = ""), '</span>') else ""

  cont_class <- if (year_label == "") " pub-cont" else ""

  cat(paste0(
    '<div class="pub-entry', cont_class, '">\n',
    '<span class="pub-year-col">', year_label, '</span>\n',
    '<div class="pub-body">\n',
    '<div class="pub-title-row">', title_html, '</div>\n',
    journal_html,
    '<div class="pub-author-row">', p$author, '</div>\n',
    links_html, '\n',
    abstract_div, '\n',
    '</div>\n',
    '</div>\n\n'
  ))
}
```


::: {.content-visible when-profile="en"}
### Pre-prints
(\*: *equal contribution*)
:::

::: {.content-visible when-profile="es"}
### Pre-prints
(\*: *igual contribución*)
:::

::: {.research-list}

```{r preprints, results='asis'}
#| echo: false

preprints <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1id1P5ke9ZJckr_6ePP84FOLeQPoHb57eitX7yaZ_l8A/edit#gid=1000751275") %>%
  filter(type == "pre-print") %>%
  mutate(author = str_replace_all(author, "G. Solovey", '<strong class="self-author">G. Solovey</strong>'))

for (i in seq_len(nrow(preprints))) {
  render_entry(preprints[i, ], use_pdf_col = FALSE, row_id = paste0("pre", i), year_label = "")
}
```

:::


::: {.content-visible when-profile="en"}
### Publications
(\*: *equal contribution*)
:::

::: {.content-visible when-profile="es"}
### Publicaciones
(\*: *contribuyeron igualitariamente*)
:::

::: {.research-list}

```{r pubs, results='asis'}
#| echo: false

pubs <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1id1P5ke9ZJckr_6ePP84FOLeQPoHb57eitX7yaZ_l8A/edit#gid=1000751275") %>%
  filter(type == "Article") %>%
  mutate(author = str_replace_all(author, "G. Solovey", '<strong class="self-author">G. Solovey</strong>')) %>%
  arrange(desc(year))

pub_counter <- 0
prev_year <- ""
for (i in seq_len(nrow(pubs))) {
  pub_counter <- pub_counter + 1
  yr <- as.character(pubs$year[i])
  year_label <- if (yr != prev_year) yr else ""
  prev_year <- yr
  render_entry(pubs[i, ], use_pdf_col = TRUE, row_id = paste0("pub", pub_counter), year_label = year_label)
}
```

:::
