---
title: ""
toc: false
editor: source
---

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
library(gsheet)
library(tidyverse)

SHEET_URL <- "https://docs.google.com/spreadsheets/d/1id1P5ke9ZJckr_6ePP84FOLeQPoHb57eitX7yaZ_l8A/edit#gid=852428719"
```

::: {.content-visible when-profile="en"}
### Courses
:::
::: {.content-visible when-profile="es"}
### Cursos
:::

```{r teaching, results='asis'}
#| echo: false

courses <- gsheet2tbl(SHEET_URL) %>%
  filter(cargo %in% c("prof", "doc")) %>%
  mutate(
    materia = ifelse(!is.na(url) & url != "",
                     paste0("[", materia, "](", url, ")"),
                     materia)
  ) %>%
  arrange(desc(year))

years <- unique(courses$year)

for (yr in years) {
  cat(paste0("#### ", yr, "\n\n"))
  yr_courses <- filter(courses, year == yr)
  for (i in seq_len(nrow(yr_courses))) {
    c <- yr_courses[i, ]
    cat(paste0(
      '::: {.pub-entry}\n',
      '**', c$materia, '**\\\n',
      '*', c$carrera, '*\n',
      ':::\n\n'
    ))
  }
}
```
